$kind: http-request
url: "{{baseUrl}}/api/v1/admin/settings"
method: PUT
headers:
  Content-Type: application/json
body:
  type: json
  content: |-
    {
      "maintenanceMode": false,
      "allowNewRegistrations": true
    }
order: 2000
